config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flats_path
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.input :picture %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <h2>Edit <%= @flat.name %></h2>
  <%= render 'form' %>
</div>

app/views/flats/index.html.erb
<div class="navbar-wagon">
  <%= link_to 'Simple Airbnb', flats_path, class: "navbar-logo" %>
  <div class="navbar-right">
  <%= link_to "Add flat", new_flat_path, class: "btn btn-primary" %></div>
  </div>
</div>

<div class="container">
  <h1>All our Flats (<%= @flats.count %>)</h1>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-4">
        <div class="card">
          <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= flat.picture %>);">
          </div>
          <div class="card-body">
            <h4><strong><%= flat.name %></strong></h4>
            <p><%= flat.address %></p>
            <p><i class="fas fa-users"></i> <%= flat.number_of_guests %>  <i class="fas fa-euro-sign"></i> <%= flat.price_per_night %></p>
          </div>
          <div class="card-footer">
            <%= link_to 'More info', flat_path(flat) %>
            <%= link_to 'Edit', edit_flat_path(flat), class: "text-warning" %>
            <%= link_to 'Remove', flat_path(flat), method: :delete, class: "text-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h2>Add a flat:</h2>
  <%= render 'form' %>
</div>

app/views/flats/show.html.erb
<div class="navbar-wagon">
  <%= link_to 'Simple Airbnb', flats_path, class: "navbar-logo" %>
  <div class="navbar-right">
  <%= link_to "Add flat", new_flat_path, class: "btn btn-primary" %></div>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= @flat.picture %>);">
</div>
<div class="container margin-negative">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="info-container">
          <div class="flat-info">
            <h2><%= @flat.name %></h2>
            <p><%= @flat.address %></p>
          </div>
          <div class="flat-info">
            <h3>A bit more about this flat...</h3>
            <p><%= @flat.description %></p>
            <div class="map">
              <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{@flat.address}&size=650x250&markers=address:#{@flat.address}" %>
            </div>
          </div>
          <div class="flat-info">
            <h3>Details</h3>
            <p><i class="fas fa-users"></i> <%= @flat.number_of_guests %>  <i class="fas fa-euro-sign"></i> <%= @flat.price_per_night %></p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="action-container">
          <div class="flat-info">
            <h4>Book this place!</h4>
            <form action="" class="form-group">
              <label for="arrival">From:</label>
              <input type="date" name="arrival" class="form-control">
              <label for="departure">To:</label>
              <input type="date" name="departure" class="form-control">
              <input type="submit" class="btn btn-success margin-top" value="Book" style="width: 100%">
            </form>
          </div>
          <div class="flat-info share">
            <p>Share</p>
            <div>
              <a href=""><i class="fab fa-facebook-square"></i></a>
              <a href=""><i class="fab fa-twitter-square"></i></a>
              <a href=""><i class="fab fa-pinterest-square"></i></a>
              <a href=""><i class="fas fa-envelope-square"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>